### POST new
POST http://localhost:3031/animal
Content-Type: application/json

{
  "animalName": "Junior",
  "species": "Dog",
  "adopted": "not yet"
}

### GET all
GET http://localhost:3031/animal


### PUT update
PUT http://localhost:3031/animal/48727f60-83a8-4dee-9598-a2de8834034a
Content-Type: application/json

{
  "animalName": "Sandro",
  "species": "Dog",
  "adopted": "yes"
}

### DELETE
DELETE http://localhost:3031/animal/48727f60-83a8-4dee-9598-a2de8834034a
